# Uncomment the next line to define a global platform for your project
platform :ios, '16.4'

target 'MyAdmob' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyAdmob
  pod 'Google-Mobile-Ads-SDK'

  target 'MyAdmobTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyAdmobUITests' do
    # Pods for testing
  end

end
